add Browser checks
corona-warn-app/cwa-event-landingpage pull request #17
Opened 2021-05-04 20:41 UTC by thomasaugsten

2021-05-04 20:44 UTC, Ein-Tim commented
That's also a way to fix #16 (-;

2021-05-05 08:33 UTC, svengabr commented on src/partials/page-index.html
> +                                <img class="img-fluid w-100" src="/assets/img/App_Store_Badge_DE.svg" alt="Apple App Store Icon" />
Image missing in repository, resulting in error 404 and no image displayed. @thomasaugsten can you please commit it?

2021-05-05 08:33 UTC, svengabr requested changes
Missing image, see my previous comment.

2021-05-05 09:35 UTC, svengabr commented on src/assets/js/app.js
> +        originalUrlElement.classList.remove("d-none");
![2021-05-05 11_34_21-Window](https://user-images.githubusercontent.com/4686874/117122197-ea71f000-ad95-11eb-8ba4-4991924f479b.png)

There is a visible printed originalUrl o the website when opening the main website and being redirected to the languageCode `/en` or `/de`

2021-05-05 09:39 UTC, svengabr requested changes
How to reproduce

1. open `localhost:8000/`
2. Getting redirected to your language
3. See the url in the center

2021-05-05 10:48 UTC, svengabr approved these changes

2021-05-05 10:48 UTC, merged